name: Build and deploy ASP.Net Core app to Azure Web App - Sistemas-ventas-Web-Victor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Ver archivos (debug)
        run: dir "Sistema de ventas Wed Victor"

      - name: Restore
        run: dotnet restore "./Sistema de ventas Wed Victor/*.sln"

      - name: Build
        run: dotnet build "./Sistema de ventas Wed Victor/*.sln" --configuration Release --no-restore

      - name: Publish (Admin)
        run: dotnet publish "./Sistema de ventas Wed Victor/CapaPresentacionAdmin/CapaPresentacionAdmin.csproj" -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_76ED22827B0E431CB78855771A18840A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8DA0DBEDCD3549159259616F3452A4C5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1BCBDA7FBB20484DAB1A329E05AC6D65 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Sistemas-ventas-Web-Victor'
          slot-name: 'Production'
          package: .
