name: Build and deploy ASP.Net Core app to Azure Web App - Sistemas-ventas-Web-Victor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Ver archivos (debug)
        run: dir "Sistema de ventas Wed Victor"

      - name: Restore
        run: nuget restore "./Sistema de ventas Wed Victor/Sistema de ventas Wed Victor.sln"

      - name: Build
        run: msbuild "./Sistema de ventas Wed Victor/Sistema de ventas Wed Victor.sln" /p:Configuration=Release /p:Platform="Any CPU"

      - name: Publish (Admin)
        run: msbuild "./Sistema de ventas Wed Victor/CapaPresentacionAdmin/CapaPresentacionAdmin.csproj" /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./Sistema de ventas Wed Victor/CapaPresentacionAdmin/bin/Release

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_76ED22827B0E431CB78855771A18840A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8DA0DBEDCD3549159259616F3452A4C5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1BCBDA7FBB20484DAB1A329E05AC6D65 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Sistemas-ventas-Web-Victor'
          slot-name: 'Production'
          package: .
